### ISSUE TITLE
stm32wbxx_hal_exti.c fails to build with -Werror=unused-parameter 

### ISSUE THREAD

**Issue by juliengros** [STMicroelectronics/STM32CubeWB#48] opened 2021-12-05 09:47 UTC
**Describe the bug**
stm32wbxx_hal_exti.c fails to build with -Werror=unused-parameter. 
![Screenshot 2021-12-05 at 10 44 27](https://user-images.githubusercontent.com/12698919/144741505-1650f27b-25e3-4379-a327-b8094282c372.png)

**Possible Fix**
The following change fixes the issue. I would be more than happy contributing but unclear to me what CLA I should get with ST to contribute. Maybe you can help me clarifying.
![Screenshot 2021-12-05 at 10 46 59](https://user-images.githubusercontent.com/12698919/144741558-360ea632-ced1-44f9-9aac-2c5bd237fd35.png)

**Comment by RKOUSTM** [comment] 2021-12-09 15:47
Hi @juliengros,

Thank you for this contribution. The procedure is very simple and is to be done just **once**. Just follow this [link](https://cla.st.com) above, read carefully the terms of the CLA, then, if you accept them, click on the `I Accept` button. Thank you for again for your contribution.

With regards,

**Comment by RKOUSTM** [comment] 2021-12-09 16:50
ST Internal Reference: 119231

**Comment by RKOUSTM** [comment] 2022-01-18 10:42
Hi @juliengros,

Thank you for your report. This duplicated issue will remain closed. The pull-request #50 that you reported will be kept open to track the point.

Thank you for you again for your report.

With regards,

**Comment by RKOUSTM** [comment] 2022-01-18 10:44
Duplicate of #50.

**Closed** 2022-01-18 10:44 UTC
Labels: bug, duplicate, internal bug tracker, hal
