### ISSUE TITLE
stm32wb connection binding problem

### ISSUE THREAD

**Issue by ChaunceyLong** [STMicroelectronics/STM32CubeWB#42] opened 2021-08-27 02:11 UTC
In using the official p2p routine, the binding inside is performed after the connection, and the effect I want is to bind or pair and then connect, how to achieve it?

**Comment by RKOUSTM** [comment] 2021-09-03 08:37
Hi @ChaunceyLong,

Thank you for your contribution.

In order to allow a better analysis of this problem, could you please give us more details about the application that you are using to reproduce this issue or did you use one of our applications? Otherwise, it is possible to share with us a code snippet allowing our development teams to reproduce it.

Also, could you please confirm you are using the latest firmware version and that the issue is systematically reproducible on your side?

Thank you again for your contribution.

With regards,

**Comment by RKOUSTM** [comment] 2021-09-16 09:32
Hi @ChaunceyLong,

According to our development teams, without more details on this issue, we unfortunately cannot investigate this issue and speed up the analysis procedure as no feedback has been received. 

Please allow me to close this issue now. You can reopen it if you have anything else relevant to add regarding this topic.

With regards,

**Closed** 2021-09-16 09:33 UTC
Labels: needs clarification
